<script lang="ts">
  import TargoNav from '$lib/components/TargoNav.svelte';
  import JsonLd from '$lib/components/JsonLd.svelte';
</script>

<svelte:head>
  <title>Privacy Policy — Tech Pixel A2H</title>
  <meta
    name="description"
    content="How Tech Pixel A2H collects, uses and protects your personal data under India's Digital Personal Data Protection Act, 2023."
  />
  <link rel="canonical" href="https://techpixela2h.com/privacy" />
  <meta name="robots" content="index, follow" />
  <meta name="theme-color" content="#12212e" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Tech Pixel A2H" />
  <meta property="og:title" content="Privacy Policy — Tech Pixel A2H" />
  <meta
    property="og:description"
    content="How Tech Pixel A2H collects, uses and protects your personal data under India's Digital Personal Data Protection Act, 2023."
  />
  <meta property="og:url" content="https://techpixela2h.com/privacy" />
  <meta property="og:image" content="https://techpixela2h.com/og/privacy.png" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt" content="Privacy Policy — Tech Pixel A2H" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="Privacy Policy — Tech Pixel A2H" />
  <meta
    name="twitter:description"
    content="How Tech Pixel A2H collects, uses and protects your personal data under India's Digital Personal Data Protection Act, 2023."
  />
  <meta name="twitter:image" content="https://techpixela2h.com/og/privacy.png" />
</svelte:head>

<JsonLd
  name="Privacy Policy — Tech Pixel A2H"
  description="How Tech Pixel A2H collects, uses and protects your personal data under India's Digital Personal Data Protection Act, 2023."
  path="/privacy"
  crumbs={[{ name: 'Privacy Policy', path: '/privacy' }]}
/>

<TargoNav active="privacy" />

<main id="main" tabindex="-1">
  <section class="targo-band-white px-6 py-24 md:py-32" aria-label="Privacy policy">
    <div class="mx-auto max-w-6xl">
      <p class="targo-eyebrow">Legal</p>
      <h1 class="targo-title mt-4">Privacy<br /><span class="t-accent">Policy</span></h1>
      <p class="targo-lead mt-6 max-w-2xl">
        Last updated: 29 September 2026. Tech Pixel A2H (“we”, “us”) respects your
        privacy and processes personal data in line with India’s Digital Personal
        Data Protection Act, 2023 (DPDP Act).
      </p>

      <div class="targo-card mt-12 p-8 md:p-12">
        <div class="targo-prose max-w-none">
          <h2>1. Who we are</h2>
          <p>
            Tech Pixel A2H is a digital services team based in India providing web
            development, AI automation, design, content and marketing services.
            Registered address: {'{{PLACEHOLDER_REGISTERED_ADDRESS}}'}. Company
            identifiers (CIN/GSTIN, where applicable): {'{{PLACEHOLDER_CIN_GSTIN}}'}.
          </p>
          <h2>2. Data we collect</h2>
          <p>We collect only what we need to respond to you and deliver our services:</p>
          <ul>
            <li>
              Contact details you share voluntarily — name, phone number, email
              address and project details submitted through our contact form,
              email, phone or WhatsApp.
            </li>
            <li>
              Consent-gated, cookieless website analytics (Plausible, EU-hosted)
              which loads only after you accept the consent banner. We set no
              advertising or cross-site tracking cookies.
            </li>
            <li>
              Basic technical logs generated by our hosting provider when you
              visit this site (e.g. IP address, browser type), retained per the
              provider’s policy.
            </li>
          </ul>
          <h2>3. Why we use it (purpose &amp; lawful basis)</h2>
          <p>
            Your data is used to respond to enquiries, prepare quotes, deliver
            contracted services, and improve this website — on the basis of your
            consent and legitimate use under the DPDP Act. We never sell your
            personal data.
          </p>
          <h2>4. Sharing</h2>
          <p>
            We share data only with processors needed to operate this site and our
            services: our form-handling provider (Basin), our analytics provider
            (Plausible, after your consent), and our hosting provider. No other
            third-party sharing takes place without your consent, except where
            required by Indian law.
          </p>
          <h2>5. Your rights under the DPDP Act, 2023</h2>
          <p>
            You may request access to, correction of, or erasure of your personal
            data; withdraw consent at any time (withdrawal does not affect prior
            lawful processing); and seek grievance redressal as described below.
            To exercise any right, contact us at {'{{PLACEHOLDER_PRIVACY_EMAIL}}'}.
          </p>
          <h2>6. Grievance redressal</h2>
          <p>
            For data-protection grievances, contact our Grievance Officer at
            {'{{PLACEHOLDER_GRIEVANCE_NAME}}'}, {'{{PLACEHOLDER_GRIEVANCE_EMAIL}}'},
            {'{{PLACEHOLDER_GRIEVANCE_PHONE}}'}. We aim to acknowledge grievances
            within 48 hours and resolve them within 30 days, in line with the
            DPDP Act timelines.
          </p>
          <h2>7. Retention &amp; security</h2>
          <p>
            Enquiry data is retained only as long as needed to handle your request
            and any resulting engagement, then deleted or anonymised. We apply
            reasonable safeguards (access control, encrypted transport) appropriate
            to a small team; no method of transmission over the internet is
            completely secure.
          </p>
          <h2>8. Children</h2>
          <p>
            This site and our services are directed at business customers. We do
            not knowingly collect data of children; verifiable consent of a
            parent or lawful guardian is required where applicable under the
            DPDP Act.
          </p>
          <h2>9. Changes to this policy</h2>
          <p>
            We will post any changes on this page with a revised “last updated”
            date. Material changes will be highlighted here for at least 30 days.
          </p>
          <h2>10. Contact</h2>
          <p>
            Questions about this policy: {'{{PLACEHOLDER_PRIVACY_EMAIL}}'},
            {'{{PLACEHOLDER_BUSINESS_PHONE}}'}, {'{{PLACEHOLDER_REGISTERED_ADDRESS}}'}.
          </p>
        </div>
      </div>
    </div>
  </section>
</main>
